name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'enhancement'
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '📝 Documentation'
    labels:
      - 'documentation'
  - title: '📦 Other Changes'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  default: patch
autolabeler:
  - label: 'bug'
    branch:
      - '/^fix\/.+/'
    title:
      - '/^fix(\(.+\))?:/i'
  - label: 'enhancement'
    branch:
      - '/^feat\/.+/'
      - '/^feature\/.+/'
    title:
      - '/^feat(\(.+\))?:/i'
  - label: 'documentation'
    branch:
      - '/^docs\/.+/'
    title:
      - '/^docs(\(.+\))?:/i'
    files:
      - '**/*.md'
  - label: 'dependencies'
    title:
      - '/^chore\(deps\)/i'
  - label: 'major'
    title:
      - '/^\w+(\(.+\))?!:/'
    body:
      - '/BREAKING CHANGE/'
template: |
  $CHANGES
footer: |

  ## 🌱 Full Changelog

  https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
